[source]
type = "N2C"
address = ["Unix", "/home/logic/Documents/Work/LogicalMechanism/full-node-wallet/node/db-testnet/node.socket"]
magic = "preprod"

[source.intersect]
type = "Point"
value = [37038451, "eabf8f2304e96d06fdc2124ab23313a775ab84e40ccdffcc18fd3eee8bc8c3cc"]

[source.mapper]
include_transaction_details = true

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Exit"
