name = "aiken-land/fractional-sale"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-land/fractional-sale'"

[repository]
user = "aiken-land"
project = "fractional-sale"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
