[source]
type = "N2C"
address = ["Unix", "/home/logic/Documents/Work/LogicalMechanism/testnet-node/node/db-testnet/node.socket"]
magic = "preprod"
min_depth = 0

[source.intersect]
type = "Point"
value = [50586790, "70aa54daad7f997176f7ad68c6048c4e09091889d03fe0acf0d126b36d1f1a5f"]

[source.mapper]
include_transaction_details = true

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Exit"
