[source]
type = "N2C"
address = ["Unix", "/home/logic/Documents/Work/LogicalMechanism/full-node-wallet/node/db-testnet/node.socket"]
magic = "preprod"

[source.intersect]
type = "Point"
value = [34117450, "529c536c02fa056874ff2e9aaa56d79b7e4d3b0fceafc1321cbd048dd9361808"]

[source.mapper]
include_transaction_details = true

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Exit"
