[source]
type = "N2C"
address = ["Unix", "/home/logic/Documents/Work/LogicalMechanism/full-node-wallet/node/db-testnet/node.socket"]
magic = "preprod"

[source.intersect]
type = "Point"
value = [34532183, "3169a6873e9191a39a50606efc15467b2a712f8f57156e9fd57b801843604b8d"]

[source.mapper]
include_transaction_details = true

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Exit"
