name = "projectNEWM/fractional-minter"
version = "2.0.0"
license = "GPLv3"
description = "Aiken contracts for Project NEWM"

[repository]
user = "aiken-lang"
project = "fractional-minter"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "main"
source = "github"
