name = "aiken-lang/fractional-minter"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/fractional-minter'"

[repository]
user = "aiken-lang"
project = "fractional-minter"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.0.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.1.5"
source = "github"
