[source]
type = "N2C"
address = ["Unix", "/home/logic/Documents/Work/LogicalMechanism/full-node-wallet/node/db-testnet/node.socket"]
magic = "preprod"

[source.intersect]
type = "Point"
value = [36890237, "0f294def7d623bba63f54910ae3ce054c6dd4c8c0308ec08f585e85d154b5c74"]

[source.mapper]
include_transaction_details = true

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Exit"
