name = "projectNEWM/order_book"
version = "0.1.0"
license = "GPLv3"
description = "Aiken contracts for Project NEWM"

[repository]
user = "aiken-lang"
project = "order_book"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "main"
source = "github"